### ISSUE TITLE
matplolib, bokeh or both?

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/arviz_dashboard#8]
currently `dashboard_elpd` uses a mix of matplotlib and bokeh. Do we want to follow this patter for other dashboards? Is there any advantage of using a mix?

Probably we should restrict dashboard to only use bokeh or matplotlib, assuming we want to support both as in regular arviz. Or maybe we should focus just on bokeh dashboards

**Comment by ndmlny-qs** [comment]
My preference would be to use the tool that allows for the most interactivity for the user, which would be Bokeh since it has a JavaScript component that is rendered in Jupyter.

I think as a first step, we should choose one plotting library to use while we work out how a dashboard could function for model diagnostics. My preference to just use Bokeh, but that is just one opinion. In the future, when there are a set of dashboards that exist and have been tested, we can think about expanding the visuals to other plotting libraries.
